# Generated by Django 3.1.7 on 2021-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210318_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tax_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
